### ISSUE TITLE
Performance other than lib size

### ISSUE THREAD

**Issue by anonym24** [IljaKosynkin/FFmpeg-Development-Kit#12]
As I understand parameters `--disable-asm --enable-small` for building FFmpeg disimproves its performance

> --disable-asm            disable all assembly optimizations
> --enable-small           optimize for size instead of speed

or `--disable-asm` does something else?

**Comment by IljaKosynkin** [comment]
@anonym24 disable asm can affect size of the library, but it's more about speed, rather then size. The main point of disabling inlined asm is not in optimization for size, but the problem with recent GCC/Clang toolchains, which seems to have problem with asm instructions in FFmpeg. Earlier it used to be a problem only on x86 platforms, since there was a problem with PIC, but now it seems like it has spread across all architectures. It's quite unlikely that I will be able to fix this, as my knowledge of Assembler is quite basic and generally condenses to few basic things that I was doing with NASM.

**Comment by anonym24** [comment]
@anonym24 compiling with ASM enabled worked ok for your FFmpeg 2 build scripts and NDK 14

now it only works ok for x86 (FFmpeg 4 and NDK 17)

we can use it like this at https://github.com/IljaKosynkin/FFmpeg-Development-Kit/blob/master/ffmpeg/build.sh#L149:

```
build "armeabi-v7a" "14" "--disable-asm"
build "arm64-v8a" "21" "--disable-asm"
build "x86_64" "21" "--disable-asm"
build "x86" "14"
```
