### ISSUE TITLE
[QUESTION] FFMPEG code source

### ISSUE THREAD

**Issue by caiomcg** [IljaKosynkin/FFmpeg-Development-Kit#17]
Hello Ilja,

Could you inform me the source of the ffmpeg repo inside of this project? I have been trying to compile ffmpeg from the source and have had several issues with libavformat/udp.c. Looking at the source of this project I noticed that the buggy section has been modified and would love to know who did it.

Thanks in advance

Caio Guedes

**Comment by IljaKosynkin** [comment]
Hey, Caio!
First of all, sorry for very late response!
It depends which version of repo you used, but I suppose the first one. I had a script in place which was removing abort() calls from FFmpeg source as it would cause native crash on Android. While I don't recall this particular file, it's probably related to that. 
Anyway, I dumped both old versions since they had a lot of issues and re-wrote integration with CMake. I suggest to check that out if you still have any issues!
Closing issue for now, feel free to re-open!
