### ISSUE TITLE
How to get Progress from ffmpeg command

### ISSUE THREAD

**Issue by rahulpawar1989** [IljaKosynkin/FFmpeg-Development-Kit#27]
Hello, First of all i want to say thanks to you for your library which is simple to use.

Now i am successfully executing commands on Android but sometimes to user i need to show progress in percentage or seconds, when FFMPEG is performing its command execution.

Can you please help me to how to get progress value from ffmpeg.

Thanks in Advance

**Comment by IljaKosynkin** [comment]
Hey!
Sorry for very later response, didn't have time to check in on the repo. 
AFAIK, there is no way to get progress from CLI, since it is not supposed to be used that way. The best you can do is to capture stdout and analyse it for the clue on the progress.
Otherwise you probably would need to write custom code that uses FFmpeg as library to get that info programmatically. 
I'm closing the issue, feel free to re-open if you still need this!
