### ISSUE TITLE
How to stop/cancel current ffmpeg execution after we called run method?

### ISSUE THREAD

**Issue by anonym24** [IljaKosynkin/FFmpeg-Development-Kit#9]
How to stop/cancel current ffmpeg execution after we called run method? https://github.com/IljaKosynkin/FFmpeg-Development-Kit/blob/master/JNI/app/src/main/java/com/example/ilja/jni/VideoKit.java#L57

**Comment by IljaKosynkin** [comment]
@anonym24 FFmpeg as CL-utility doesn't really support this, thus this Kit doesn't support it as well. Note that this Kit is just helper for the building of FFmpeg on mobile platform and will not change FFmpeg code, unless it affects work on target platform (i.e. causes crash due to abort() or exit() calls). In order to support such functionality you need to change ffmpeg code manually.
Sorry for the late response!
